### ISSUE TITLE
MongoError when sending SR from template

### ISSUE THREAD

**Issue by Framinus** [Framinus/nodejs-demo#8]
Happens when creating a signature request from the W-4 template. The request successfully processes, but the data is not getting pushed to the database.

This is the error text: 

{ MongoError: Unknown modifier: $pushAll
    at Function.MongoError.create (/Users/REDACTED/Desktop/AWS-Test/demo/nodejs-demo/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/Users/REDACTED/Desktop/AWS-Test/demo/nodejs-demo/node_modules/mongodb/lib/utils.js:139:22)
    at /Users/REDACTED/Desktop/AWS-Test/demo/nodejs-demo/node_modules/mongodb/lib/collection.js:1059:67
    at /Users/REDACTED/Desktop/AWS-Test/demo/nodejs-demo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'Unknown modifier: $pushAll',
  driver: true,
  index: 0,
  code: 9,
  errmsg: 'Unknown modifier: $pushAll' }

**Comment by Framinus** [comment]
Error also happens when sending the signature request from the mutual NDA. My guess is that it's going to happen on all of them.

**Comment by Framinus** [comment]
Issue was caused by having a newer version of MongoDB on my local machine. Inserting this line after requiring Mongoose fixed the error: mongoose.plugin(schema => { schema.options.usePushEach = true });
